[package]
name = "iced-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "*"
libmath = "*"
winapi = "*"
[target.'cfg(macos)']
num_cpus = "1.13.1"